# Generated by Django 4.2.3 on 2023-07-18 19:32

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
